name: Build and Publish Docker Images

on:
  schedule:
    - cron: '30 12 * * 1'
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  BASE_IMAGES: backgrounds

jobs:
  build_and_publish:
    name: build, test and publish
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    -
      name: Login to GitHub Container Registry
      uses: docker/login-action@v1 
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}      
    -
      name: publish bosh-cli-v2 image
      uses: docker/build-push-action@v2
      with:
        context: ${{env.IMAGE}}
        push: true
        tags: |
          ghcr.io/${{ github.repository }}/${{env.IMAGE}}:latest
          ghcr.io/${{ github.repository }}/${{env.IMAGE}}:${{github.sha}}
      env:
        IMAGE: backgrounds


  check_published_images:
    name: check published images
    runs-on: ubuntu-latest
    needs: [ build_and_publish ]
    steps:
      # We do not require authentication as package should be public !
      -
        name: check docker public images
        run: |
          for image in $BASE_IMAGES;do
            echo "Processing $image"
            docker manifest inspect ghcr.io/${GITHUB_REPOSITORY}/$image:$GITHUB_SHA
          done
